[[main]]
none = "none"

[[main]]
name = "Posts"
pageRef = "posts"
identifier = "VJop0Aq5A2"
weight = 9_999

[[main]]
name = "Projects"
pageRef = "projects"
identifier = "fmjjbTcOXQ"
weight = 9_999

[[footer]]
none = "none"
